homepage:
  path: /
  controller: App\Controller\HomeController::index

newPerson:
  path: /person/new
  controller: App\Controller\PersonController::new

addPerson:
  path: /person/add
  controller: App\Controller\PersonController::add